### ISSUE TITLE
eufy-security-client

### ISSUE THREAD

**Issue by freddeh** [Roadrunner1106/FHEM-eufySecurity#13]
Hi Roadrunner,

Are you aware of following lib? It might be worthwhile to check if it can help adding functions to this FHEM module.

https://github.com/bropat/eufy-security-client

Sorry if this is the wrong place to put, but I did not find any way of sending a PM to you.

best regards
freddeh

**Comment by Roadrunner1106** [comment]
I know this library and have also used it for the development of the FHEM module
